const make = (id, title, category, tone, length, setup, blanks) => ({
  id,
  title,
  category,
  tone,
  length,
  age: "child",
  tags: [category, tone],
  description: `A ${tone.toLowerCase()} ${category.toLowerCase()} story with ${blanks.length} surprises.`,
  blanks,
  paragraphs: [setup],
});
const b = (id, prompt, hint, examples) => ({ id, prompt, hint, examples });
const standard = [
  b("adjective", "an adjective", "A describing word.", ["gigantic", "sparkly", "wobbly"]),
  b("noun", "a thing", "Any person, place, or thing.", [
    "trombone",
    "pancake",
    "volcano",
  ]),
  b("verb", "an action word", "Something you can do.", ["zoom", "wiggle", "whisper"]),
  b("place", "a place", "Somewhere you could visit.", [
    "the moon",
    "a library",
    "a treehouse",
  ]),
];
const entries = [
  [
    "sneezing-dragon",
    "The Sneezing Dragon",
    "Fantasy",
    "Silly",
    "Quick",
    "The {adjective} dragon sneezed so hard that a {noun} flew into {place}. Everyone had to {verb} before it landed.",
  ],
  [
    "penguin-principal",
    "Principal Penguin",
    "School",
    "Cute",
    "Quick",
    "At school, Principal Penguin announced that every {noun} must {verb} in {place}. It was a very {adjective} assembly.",
  ],
  [
    "backpack-monster",
    "The Backpack Monster",
    "School",
    "Spooky",
    "Medium",
    "A tiny monster lived in my backpack. It collected one {noun}, wore a {adjective} hat, and loved to {verb} near {place}.",
  ],
  [
    "space-picnic",
    "Space Picnic",
    "Adventure",
    "Chaotic",
    "Medium",
    "Our rocket landed at {place} for a picnic. We unpacked {noun}, then a {adjective} astronaut began to {verb}.",
  ],
  [
    "slime-cafe",
    "The Slime Café",
    "Everyday Life",
    "Gross",
    "Quick",
    "The café served {adjective} slime with a side of {noun}. The waiter said to {verb} before leaving {place}.",
  ],
  [
    "wizard-laundry",
    "Wizard Laundry Day",
    "Fantasy",
    "Silly",
    "Medium",
    "The wizard washed a {noun} and accidentally made it {adjective}. It started to {verb} all the way to {place}.",
  ],
  [
    "beach-detectives",
    "Beach Detectives",
    "Adventure",
    "Calm/Cozy",
    "Medium",
    "At {place}, the detectives found a {adjective} clue: a {noun} that could {verb}. The mystery was solved before sunset.",
  ],
  [
    "haunted-cupcake",
    "The Haunted Cupcake",
    "Holidays/Seasonal",
    "Spooky",
    "Quick",
    "A {adjective} cupcake floated out of {place}. It whispered about a missing {noun} and asked us to {verb}.",
  ],
  [
    "snow-day-parade",
    "Snow Day Parade",
    "Holidays/Seasonal",
    "Cute",
    "Medium",
    "On a {adjective} snow day, a {noun} led a parade through {place} while everyone tried to {verb}.",
  ],
  [
    "robot-pet",
    "My Robot Pet",
    "Everyday Life",
    "Chaotic",
    "Quick",
    "My robot pet is {adjective}. It eats {noun}, likes to {verb}, and sleeps in {place}.",
  ],
  [
    "jungle-library",
    "Jungle Library",
    "Animals",
    "Adventure",
    "Long",
    "The jungle library had a {adjective} librarian. A {noun} learned to {verb} and returned every book to {place}.",
  ],
  [
    "cookie-kingdom",
    "Cookie Kingdom",
    "Fantasy",
    "Cute",
    "Medium",
    "In Cookie Kingdom, the {adjective} ruler rode a {noun} to {place} and told everyone to {verb}.",
  ],
  [
    "gross-science",
    "Gross Science Fair",
    "School",
    "Gross",
    "Medium",
    "My science project mixed {noun} with something {adjective}. It began to {verb} across {place}, so the judges cheered.",
  ],
  [
    "sleepy-yeti",
    "Sleepy Yeti",
    "Animals",
    "Calm/Cozy",
    "Quick",
    "A {adjective} yeti wanted a {noun} for bedtime. It liked to {verb} quietly near {place}.",
  ],
  [
    "pirate-pajamas",
    "Pirate Pajamas",
    "Adventure",
    "Silly",
    "Medium",
    "Captain Pajamas found a {adjective} map inside a {noun}. It told the crew to {verb} toward {place}.",
  ],
  [
    "alien-substitute",
    "Alien Substitute",
    "School",
    "Chaotic",
    "Long",
    "Our substitute teacher was an alien. It called every {noun} {adjective} and taught us to {verb} at {place}.",
  ],
  [
    "rainy-cabin",
    "Rainy Cabin",
    "Holidays/Seasonal",
    "Calm/Cozy",
    "Quick",
    "At {place}, rain tapped on the roof while a {adjective} {noun} began to {verb}.",
  ],
  [
    "unicorn-gym",
    "Unicorn Gym Class",
    "Fantasy",
    "Cute",
    "Medium",
    "In gym class, a {adjective} unicorn carried a {noun} and taught us to {verb} around {place}.",
  ],
  [
    "zoo-sleepover",
    "Zoo Sleepover",
    "Animals",
    "Silly",
    "Long",
    "During our zoo sleepover, a {adjective} animal borrowed a {noun}. It tried to {verb} inside {place}.",
  ],
  [
    "pumpkin-bus",
    "Pumpkin Bus",
    "Holidays/Seasonal",
    "Spooky",
    "Quick",
    "A {adjective} pumpkin drove a bus to {place}. Everyone brought a {noun} and began to {verb}.",
  ],
  [
    "tiny-town",
    "Tiny Town Trouble",
    "Everyday Life",
    "Cute",
    "Medium",
    "In Tiny Town, a {adjective} {noun} got lost. We helped it {verb} home through {place}.",
  ],
  [
    "dinosaur-museum",
    "Dinosaur Museum",
    "Adventure",
    "Adventure",
    "Long",
    "At {place}, a dinosaur found a {adjective} {noun}. It began to {verb}, and the museum guards followed.",
  ],
  [
    "mystery-soup",
    "Mystery Soup",
    "Everyday Life",
    "Gross",
    "Quick",
    "The soup was {adjective} and contained a {noun}. I had to {verb} before tasting it at {place}.",
  ],
  [
    "fairy-mail",
    "Fairy Mail",
    "Fantasy",
    "Calm/Cozy",
    "Medium",
    "A {adjective} fairy delivered a {noun} to {place}. Its note said, ‘Please {verb} today.’",
  ],
  [
    "school-talent",
    "School Talent Show",
    "School",
    "Silly",
    "Long",
    "For the talent show, I wore a {adjective} {noun} and planned to {verb} onstage at {place}.",
  ],
  [
    "moon-camp",
    "Moon Camp",
    "Adventure",
    "Adventure",
    "Medium",
    "At moon camp, we built a {adjective} {noun} and learned to {verb} outside {place}.",
  ],
  [
    "spider-tea",
    "Spider Tea Party",
    "Animals",
    "Spooky",
    "Quick",
    "A {adjective} spider invited a {noun} to tea at {place}, where they learned to {verb}.",
  ],
  [
    "cozy-market",
    "Cozy Market",
    "Everyday Life",
    "Calm/Cozy",
    "Medium",
    "At {place}, we bought a {adjective} {noun} and watched people {verb} past the windows.",
  ],
  [
    "monster-holiday",
    "Monster Holiday",
    "Holidays/Seasonal",
    "Chaotic",
    "Long",
    "The monster holiday began when a {adjective} {noun} arrived at {place} and everyone had to {verb}.",
  ],
  [
    "magic-paint",
    "Magic Paint",
    "Fantasy",
    "Silly",
    "Medium",
    "A {adjective} paintbrush painted a {noun} that could {verb} around {place}.",
  ],
];
export const madLibTemplates = entries.map(
  ([id, title, category, tone, length, story], index) =>
    make(
      id,
      title,
      category,
      tone,
      length,
      story,
      standard.map((item) => ({ ...item, id: `${item.id}-${index}` }))
    )
);
export const madLibById = (id) => madLibTemplates.find((template) => template.id === id);
