import { ArrowLeft, Palette, RotateCcw, Undo2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";

import { EmptyState, Page } from "../../components/layout";
import "./GamesPage.css";

const assets = import.meta.glob("../../assets/visual-games/*", { eager: true, import: "default", query: "?url" });
const titleFor = (path) => path.split("/").pop().replace(/^vecteezy_/, "").replace(/_[0-9]+(?:-[0-9]+)?\.jpg$/, "").replaceAll("-", " ");
const colors = ["#ffc51c", "#aee7ed", "#31add2", "#b7d58c", "#82a43a", "#ba7345", "#ececec", "#e56b7b", "#ffffff"];
function kindFor(id) { if (/color-by-number/.test(id)) return "color"; if (/dot-to-dot/.test(id)) return "dots"; if (/difference/.test(id)) return "difference"; return "find"; }
function fill(context, x, y, color) {
  const canvas = context.canvas; const image = context.getImageData(0, 0, canvas.width, canvas.height); const data = image.data; const start = (y * canvas.width + x) * 4; const base = data.slice(start, start + 4);
  if (base[3] < 16 || base[0] < 185 || base[1] < 185 || base[2] < 185) return false;
  const hex = color.match(/\w\w/g).map((part) => Number.parseInt(part, 16)); const queue = [[x, y]]; const seen = new Set();
  while (queue.length) { const [cx, cy] = queue.pop(); const key = `${cx}:${cy}`; if (seen.has(key) || cx < 0 || cy < 0 || cx >= canvas.width || cy >= canvas.height) continue; seen.add(key); const index = (cy * canvas.width + cx) * 4; if (Math.abs(data[index] - base[0]) > 28 || Math.abs(data[index + 1] - base[1]) > 28 || Math.abs(data[index + 2] - base[2]) > 28) continue; data[index] = hex[0]; data[index + 1] = hex[1]; data[index + 2] = hex[2]; data[index + 3] = 255; queue.push([cx + 1, cy], [cx - 1, cy], [cx, cy + 1], [cx, cy - 1]); }
  context.putImageData(image, 0, 0); return true;
}

export default function VisualGameCanvasPage() {
  const { imageId } = useParams(); const [marks, setMarks] = useState([]); const [color, setColor] = useState(colors[0]); const [history, setHistory] = useState([]); const canvasRef = useRef(null);
  const game = useMemo(() => Object.entries(assets).map(([path, image]) => ({ id: path.split("/").pop(), image, title: titleFor(path) })).find(({ id }) => id === imageId), [imageId]); const kind = kindFor(imageId ?? "");
  useEffect(() => { if (!game || kind === "color") return; setMarks([]); }, [game, kind]);
  useEffect(() => { if (!game || kind !== "color") return; const canvas = canvasRef.current; const image = new Image(); image.onload = () => { canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; canvas.getContext("2d", { willReadFrequently: true }).drawImage(image, 0, 0); setHistory([]); }; image.src = game.image; }, [game, kind]);
  if (!game) return <Page title="Visual Game Not Found"><EmptyState action={<Link className="studio-button studio-button--primary" to="/games/visual">Back to Visual Activities</Link>} title="We couldn’t find that activity." /></Page>;
  const addMark = (event) => { const rect = event.currentTarget.getBoundingClientRect(); setMarks((items) => [...items, { id: `${Date.now()}-${items.length}`, x: ((event.clientX - rect.left) / rect.width) * 100, y: ((event.clientY - rect.top) / rect.height) * 100 }]); };
  const paint = (event) => { const canvas = canvasRef.current; const rect = canvas.getBoundingClientRect(); const x = Math.floor((event.clientX - rect.left) * (canvas.width / rect.width)); const y = Math.floor((event.clientY - rect.top) * (canvas.height / rect.height)); const context = canvas.getContext("2d", { willReadFrequently: true }); const before = canvas.toDataURL(); if (fill(context, x, y, color)) setHistory((items) => [...items, before]); };
  const copy = kind === "color" ? "Choose a color, then tap a numbered white space to fill it." : kind === "dots" ? "Tap or click each dot to mark your path." : kind === "difference" ? "Tap or click every difference you spot to circle it." : "Tap or click anything you find to circle it.";
  return <Page actions={<Link className="studio-button studio-button--secondary" to="/games/visual"><ArrowLeft size={17} /> Back to Visual Activities</Link>} className="visual-game-canvas-page" description={copy} title={game.title}><section className="visual-game-canvas"><div className="visual-game-canvas__toolbar"><p>{kind === "color" ? "Choose a color, then fill the numbered boxes." : marks.length ? `${marks.length} mark${marks.length === 1 ? "" : "s"} placed` : copy}</p><div>{kind === "color" ? <button className="studio-button studio-button--secondary" disabled={!history.length} onClick={() => { const previous = history.at(-1); const image = new Image(); image.onload = () => canvasRef.current.getContext("2d").drawImage(image, 0, 0); image.src = previous; setHistory((items) => items.slice(0, -1)); }} type="button"><Undo2 size={17} /> Undo</button> : <button className="studio-button studio-button--secondary" disabled={!marks.length} onClick={() => setMarks((items) => items.slice(0, -1))} type="button"><Undo2 size={17} /> Undo</button>}<button className="studio-button studio-button--secondary" disabled={kind === "color" ? !history.length : !marks.length} onClick={() => { if (kind === "color") { const image = new Image(); image.onload = () => canvasRef.current.getContext("2d").drawImage(image, 0, 0); image.src = game.image; setHistory([]); } else setMarks([]); }} type="button"><RotateCcw size={17} /> Clear</button></div></div>{kind === "color" ? <div className="color-by-number"><div className="color-by-number__palette" aria-label="Color choices">{colors.map((swatch, index) => <button aria-label={`Color ${index + 1}`} aria-pressed={color === swatch} className="color-by-number__swatch" key={swatch} onClick={() => setColor(swatch)} style={{ backgroundColor: swatch }} type="button">{index + 1}</button>)}</div><div className="visual-game-canvas__image"><canvas aria-label="Color by number activity. Select a color then click a numbered white section." onPointerUp={paint} ref={canvasRef} /></div></div> : <div className="visual-game-canvas__image" onPointerUp={addMark} role="application" aria-label="Puzzle image. Tap or click to place a circle."><img alt="Visual puzzle" draggable="false" src={game.image} />{marks.map((mark) => <span className="visual-game-canvas__mark" key={mark.id} style={{ left: `${mark.x}%`, top: `${mark.y}%` }} />)}</div>}</section></Page>;
}
