import { BookOpen, Brain, Gamepad2, Image, Palette, Sparkles, Wand2 } from "lucide-react";

export const activityRegistry = Object.freeze([
  {
    id: "mad-libs",
    name: "Mad Libs",
    type: "game",
    description: "Collect silly words, then reveal a surprise story.",
    Icon: BookOpen,
    tags: ["Words", "Story"],
    goals: ["Social", "Executive Functioning"],
    age: "any",
    format: "shared",
    route: "/activities/mad-libs",
    supportsInvite: true,
    supportsFullscreen: true,
  },
  {
    id: "spot-it",
    name: "Spot It",
    type: "game",
    description: "Find the one picture both cards share.",
    Icon: Sparkles,
    tags: ["Visual", "Matching"],
    goals: ["Attention", "Regulation"],
    age: "child",
    format: "shared",
    route: "/games/spot-it",
    supportsInvite: true,
    supportsFullscreen: true,
  },
  {
    id: "memory-match",
    name: "Memory Match",
    type: "game",
    description: "Find pairs together in a fixed visual board.",
    Icon: Brain,
    tags: ["Matching", "Memory"],
    goals: ["Attention", "Executive Functioning"],
    age: "child",
    format: "shared",
    route: "/games/memory",
    supportsInvite: true,
    supportsFullscreen: true,
  },
  {
    id: "prompt-path",
    name: "Prompt Path",
    type: "game",
    description: "Spin through a prompt-led conversation together.",
    Icon: Sparkles,
    tags: ["Conversation", "Prompts"],
    goals: ["Coping", "Social"],
    age: "any",
    format: "shared",
    route: "/games/prompt-spinner",
    supportsInvite: true,
    supportsFullscreen: false,
  },
  {
    id: "game-library",
    name: "Game Library",
    type: "game",
    description: "Open or manage your Trivia and Bingo sets.",
    Icon: Gamepad2,
    tags: ["Trivia", "Bingo"],
    goals: ["Social", "Coping"],
    age: "any",
    format: "therapist",
    route: "/games",
    supportsInvite: false,
    supportsFullscreen: false,
  },
  {
    id: "visual-activities",
    name: "Visual Activities",
    type: "activity",
    description: "Explore licensed find, circle, and coloring activities.",
    Icon: Image,
    tags: ["Visual", "Find & Circle"],
    goals: ["Attention", "Regulation"],
    age: "child",
    format: "therapist",
    route: "/games/visual",
    supportsInvite: false,
    supportsFullscreen: false,
  },
  {
    id: "scene-builder",
    name: "Scene Builder",
    type: "builder",
    description: "Create reusable visual scenes for a session.",
    Icon: Palette,
    tags: ["Visual", "Create"],
    goals: ["Regulation", "Social"],
    age: "any",
    format: "therapist",
    route: "/scene-builder",
    supportsInvite: false,
    supportsFullscreen: false,
    status: "Coming soon",
  },
  {
    id: "comic-builder",
    name: "Comic Builder",
    type: "builder",
    description: "Plan visual stories and social scenarios.",
    Icon: Wand2,
    tags: ["Stories", "Visual"],
    goals: ["Social", "Coping"],
    age: "child",
    format: "therapist",
    route: null,
    supportsInvite: false,
    supportsFullscreen: false,
    status: "Planned",
  },
]);

export const activityTypes = Object.freeze(["game", "activity", "builder"]);
export const activityById = (id) =>
  activityRegistry.find((activity) => activity.id === id);
